### ISSUE TITLE
[vscode] "Couldn't start client Pyre Language Client"

### ISSUE THREAD

**Issue by samuela** [facebook/pyre-check#183]
I have a `.pyre_configuration` file in my project root:
```
{
  "source_directories": [
    "."
  ]
}
```
and I just installed the `fb-pyre-check` extension, but it errors out when running: `Couldn't start client Pyre Language Client`. In the Output pane I see
```
[Error - 2:17:58 PM] Starting client failed
Launching server using command pyre failed.
```
Reloading the window doesn't work either.

I have `pyre-check` installed via pipenv and I'm running vscode Version 1.36.0-insider (1.36.0-insider) on macOS 10.14.4.

**Comment by dkgi** [comment]
@samuela, sorry for the delay. Just to clarify: if you run `pyre` in the directory with your configuration everything works?

**Comment by samuela** [comment]
@dkgi Yes, that's correct. I can still run `pyre check` from the command line.

**Comment by SamChou19815** [comment]
@samuela Pyre language client invokes `pyre persistent` and in the previous released version `pyre persistent` is broken. Now `pyre persistent` no longer crashes. Could you try the latest version and see if that works for you?

**Comment by samuela** [comment]
Ok, I've now upgraded to `pyre-check==0.0.28` and the vscode extension still doesn't work, but it appears as though `pyre persistent` is working:
```
$ pipenv run pyre --search-path=$(pipenv --venv)/lib/python3.7/site-packages/ persistent
2019-07-09 12:08:37,471 DEBUG Reading configuration `.pyre_configuration`...
2019-07-09 12:08:37,477 DEBUG Found source_directories: `.`
2019-07-09 12:08:37,478 INFO No binary specified, looking for `pyre.bin` in PATH
2019-07-09 12:08:37,478 INFO Found: `/Users/skainswo/.local/share/virtualenvs/research-CJWjSlE2/bin/pyre.bin`
2019-07-09 12:08:37,478 INFO No typeshed specified, looking for it
2019-07-09 12:08:37,479 DEBUG Trying with: `/Users/skainswo/.local/share/virtualenvs/research-CJWjSlE2/lib/python3.7/site-packages/pyre_check/pyre_check/typeshed/`
2019-07-09 12:08:37,479 DEBUG Trying with: `/Users/skainswo/.local/share/virtualenvs/research-CJWjSlE2/lib/python3.7/site-packages/pyre_check/typeshed/`
2019-07-09 12:08:37,479 DEBUG Trying with: `/Users/skainswo/.local/share/virtualenvs/research-CJWjSlE2/lib/python3.7/pyre_check/typeshed/`
2019-07-09 12:08:37,479 DEBUG Trying with: `/Users/skainswo/.local/share/virtualenvs/research-CJWjSlE2/lib/pyre_check/typeshed/`
2019-07-09 12:08:37,479 INFO Found: `/Users/skainswo/.local/share/virtualenvs/research-CJWjSlE2/lib/pyre_check/typeshed/`
2019-07-09 12:08:37,481 DEBUG Running `/Users/skainswo/.local/share/virtualenvs/research-CJWjSlE2/bin/pyre.bin start -logging-sections parser -project-root /Users/skainswo/dev/research -filter-directories /Users/skainswo/dev/research -workers 1 -expected-binary-version unversioned -search-path /Users/skainswo/.local/share/virtualenvs/research-CJWjSlE2/lib/python3.7/site-packages,/Users/skainswo/.local/share/virtualenvs/research-CJWjSlE2/lib/pyre_check/typeshed/stdlib/3.7,/Users/skainswo/.local/share/virtualenvs/research-CJWjSlE2/lib/pyre_check/typeshed/stdlib/3.6,/Users/skainswo/.local/share/virtualenvs/research-CJWjSlE2/lib/pyre_check/typeshed/stdlib/3.5,/Users/skainswo/.local/share/virtualenvs/research-CJWjSlE2/lib/pyre_check/typeshed/stdlib/3,/Users/skainswo/.local/share/virtualenvs/research-CJWjSlE2/lib/pyre_check/typeshed/stdlib/2and3,/Users/skainswo/.local/share/virtualenvs/research-CJWjSlE2/lib/pyre_check/typeshed/third_party/3.5,/Users/skainswo/.local/share/virtualenvs/research-CJWjSlE2/lib/pyre_check/typeshed/third_party/3,/Users/skainswo/.local/share/virtualenvs/research-CJWjSlE2/lib/pyre_check/typeshed/third_party/2and3 .`
2019-07-09 12:08:37,513 INFO Starting up server...
2019-07-09 12:08:37,513 INFO Running as pid: 7523
2019-07-09 12:08:37,513 INFO Version: 720bcf1ac9ededebe0d395d32e7e7f0205f80c5e
2019-07-09 12:08:37,515 INFO Build info: Darwin x86_64 @ Wed May 01 2019 (development build)
2019-07-09 12:08:37,525 WARNING Failed to initialize file monitor: Could not find a watchman directory from the current directory `/Users/skainswo/dev/research`
2019-07-09 12:08:37,526 DEBUG Running `/Users/skainswo/.local/share/virtualenvs/research-CJWjSlE2/bin/pyre.bin persistent -log-identifier "." -expected-binary-version unversioned .`
2019-07-09 12:08:37,616 INFO Server starting in background

... a long time ...

^C2019-07-09 12:11:15,671 WARNING Interrupted by user
2019-07-09 12:11:15,683 DEBUG Traceback (most recent call last):
  File "/Users/skainswo/.local/share/virtualenvs/research-CJWjSlE2/lib/python3.7/site-packages/pyre_check/pyre.py", line 522, in main
    command(arguments, configuration, analysis_directory)
  File "/Users/skainswo/.local/share/virtualenvs/research-CJWjSlE2/lib/python3.7/site-packages/pyre_check/commands/command.py", line 134, in run
    self._run()
  File "/Users/skainswo/.local/share/virtualenvs/research-CJWjSlE2/lib/python3.7/site-packages/pyre_check/commands/persistent.py", line 30, in _run
    self._call_client(command=self.NAME, capture_output=False).check()
  File "/Users/skainswo/.local/share/virtualenvs/research-CJWjSlE2/lib/python3.7/site-packages/pyre_check/commands/command.py", line 258, in _call_client
    process.wait()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 990, in wait
    return self._wait(timeout=timeout)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1624, in _wait
    (pid, sts) = self._try_wait(0)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1582, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
```

**Comment by SamChou19815** [comment]
@samuela You might need to reopen vscode after you just run `pyre init`. You don't have to run `pyre persistent` to enable anything. It's designed to be automatically run by LSP client. If that still doesn't help, could you provide a minimum repro setup?

**Comment by samuela** [comment]
@SamChou19815 I already have run `pyre init` and have a `.pyre_configuration` file in the root of my project:
```json
{
  "source_directories": [
    "."
  ]
}
```

**Comment by SamChou19815** [comment]
@samuela Do you have watchman setup?

**Comment by samuela** [comment]
I have watchman installed via homebrew, but I'm not sure that it's playing nicely with pyre:
```
$ pyre incremental
 ƛ Starting server at `.`.
 ƛ Failed to initialize file monitor: Could not find a watchman directory from the current directory `/Users/skainswo/dev/research`
...
```

**Comment by SamChou19815** [comment]
@samuela  Looks like we currently don't have good documentation on that the watchman: #179. You can create an .watchmanconfig with content `{}`.

**Comment by samuela** [comment]
@SamChou19815 Thanks for that tip! I can now run `pyre incremental` in the command line without any issues, but I'm still getting the same error in VSCode.

**Comment by SamChou19815** [comment]
@samuela what's the error you are getting in vscode?

**Comment by samuela** [comment]
```
[Error - 2:17:58 PM] Starting client failed
Launching server using command pyre failed.
```

**Comment by Tatsh** [comment]
I think this is an issue with `PATH` and if you are using a virtualenv. I manually fixed the extension code to have the full path to Pyre and it works now. The extension should search for Pyre in the same bin path as the virtualenv, which is what the Python language extension does for things it supports like flake8, black, mypy, etc.

**Comment by MaggieMoss** [comment]
Closing this issue. @samuela let me know if you're still experiencing this issue on recent versions of Pyre.

**Comment by aspeddro** [comment]
I keep getting this error:

```
[Error - 5:32:13 PM] Starting client failed
Launching server using command pyre failed.
```

`.pyre_configuration`
```json
{
  "binary": "/home/pedro/Desktop/pyre-check/env/bin/pyre.bin",
  "source_directories": [
    "src"
  ]
}
```

The command `pyre` works on terminal:

```sh
> pyre     
ƛ Using virtual environment site-packages in search path...
ƛ Found 2 type errors!
src/test.py:1:0 Incompatible variable type [9]: i is declared to have type `int` but is used as type `str`.
src/test.py:3:0 Incompatible variable type [9]: o is declared to have type `str` but is used as type `int`.
```

**Comment by davclark** [comment]
It appears that vscode-pyre still won't use a project venv. I tried setting the binary path (as suggested by @aspeddro above) and this doesn't fix the "Couldn't start..." issue. You can enable the extension by installing pyre-check in your "default" python (i.e., the one that would be found without activating a project-local env).

**Comment by arjun-menon** [comment]
> It appears that vscode-pyre still won't use a project venv.

Unfortunately, still the case.

**Comment by vtgruk** [comment]
Would it be possible to get pyre to use a virtualenv? I don't want to pollute my default Python with the dependencies of every project I work with.
