### ISSUE TITLE
Unable to run pyre after pip instal

### ISSUE THREAD

**Issue by ERiverIllini** [facebook/pyre-check#19]
I pip installed pyre on my Ubuntu 16.04 machine and attempting to run the pyre command is immediately met with a syntax error. Error message below

Traceback (most recent call last):
  File "/home/emilior/Desktop/showdown/dev_work/env/bin/pyre", line 7, in <module>
    from pyre_check.pyre import main
  File "/home/emilior/Desktop/showdown/dev_work/env/lib/python3.5/site-packages/pyre_check/__init__.py", line 22, in <module>
    from . import buck
  File "/home/emilior/Desktop/showdown/dev_work/env/lib/python3.5/site-packages/pyre_check/buck.py", line 11, in <module>
    from . import log
  File "/home/emilior/Desktop/showdown/dev_work/env/lib/python3.5/site-packages/pyre_check/log.py", line 64
    _terminate: bool = False

**Comment by JelleZijlstra** [comment]
Looks like this is because Pyre only supports Python 3.6+, and you are running 3.5.
