### ISSUE TITLE
bug with infer: No such file or directory

### ISSUE THREAD

**Issue by caleb15** [facebook/pyre-check#203]
```
@caleb ➜ fifteen5 git:(dev) ✗ pyre --source-directory typeTest infer -i
 ƛ Setting up a `.pyre_configuration` with `pyre init` may reduce overhead.
 ƛ Deleting /home/caleb/Documents/fifteen5/.pyre/types
 ƛ Outputting inferred stubs to /home/caleb/Documents/fifteen5/.pyre/types
 ƛ [Errno 2] No such file or directory: 'retype': 'retype'
 ƛ Traceback (most recent call last):
  File "/home/caleb/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pyre_check/pyre.py", line 530, in main
    command(arguments, configuration, analysis_directory)
  File "/home/caleb/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pyre_check/commands/infer.py", line 417, in run
    annotate_paths(self._arguments, stubs, type_directory)
  File "/home/caleb/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pyre_check/commands/infer.py", line 355, in annotate_paths
    str(stub.path(project_directory)).rstrip("i"),
  File "/home/caleb/.pyenv/versions/3.6.4/lib/python3.6/subprocess.py", line 286, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/home/caleb/.pyenv/versions/3.6.4/lib/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/home/caleb/.pyenv/versions/3.6.4/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/home/caleb/.pyenv/versions/3.6.4/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'retype': 'retype'
```

I got this when running against the following file:
https://gist.github.com/caleb15/a05e10cf6117360dc84091bac63aeac9

I simplified the file into just `x = "foo"`, ran again, and then I go this error:

```
@caleb ➜ fifteen5 git:(dev) ✗ pyre --source-directory typeTest infer -i
 ƛ Setting up a `.pyre_configuration` with `pyre init` may reduce overhead.
 ƛ Deleting /home/caleb/Documents/fifteen5/.pyre/types
 ƛ Outputting inferred stubs to /home/caleb/Documents/fifteen5/.pyre/types
 ƛ [Errno 2] No such file or directory: 'arc': 'arc'
 ƛ Traceback (most recent call last):
  File "/home/caleb/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pyre_check/pyre.py", line 530, in main
    command(arguments, configuration, analysis_directory)
  File "/home/caleb/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pyre_check/commands/infer.py", line 417, in run
    annotate_paths(self._arguments, stubs, type_directory)
  File "/home/caleb/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pyre_check/commands/infer.py", line 371, in annotate_paths
    stderr=FNULL,
  File "/home/caleb/.pyenv/versions/3.6.4/lib/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/home/caleb/.pyenv/versions/3.6.4/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/home/caleb/.pyenv/versions/3.6.4/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'arc': 'arc'
```

I simplified again by running it against a _empty_ file and got the same error.

Looking at `pyre infer -h` it mentions I need retype so that makes sense. https://pyre-check.org/docs/guided-tour.html#using-pyre-infer should mention that retype is needed though. But what is arc?

**Comment by MaggieMoss** [comment]
@caleb15 Apologies for the frustrating experience. We've removed infers calls to `arc` in the most recent versions of Pyre.

**Comment by caleb15** [comment]
I ended up recommending that our company go with mypy as their type-checker but I appreciate the bugfixing. I'll probably end up using pyre for the security analysis sometime.
