### ISSUE TITLE
pip install fails with FileNotFoundError

### ISSUE THREAD

**Issue by lainiwa** [facebook/pyre-check#209]
Installing the latest version from PyPI (`0.0.31`) fails with the following:
```py
# pip install pyre-check
Collecting pyre-check
  Using cached https://files.pythonhosted.org/packages/97/c0/f7a1b73dbf71f3b58713cf246d594f23297ed5c5388afa198708e9a16e4b/pyre-check-0.0.31.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-95lsyiuc/pyre-check/setup.py", line 25, in <module>
        with open('README.md') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-95lsyiuc/pyre-check
```

However `pip install pyre-check==0.0.30` works fine.

Python version `3.7.4`, pip version `7.1.2`.

**Comment by lainiwa** [comment]
Must be an issue on my side.
I managed to install in into a clean `venv` successfully.
