### ISSUE TITLE
pyre don't run with version 0.0.34

### ISSUE THREAD

**Issue by jimmylai** [facebook/pyre-check#222]
Try running pyre on Macbook after upgrade to 0.0.34. Looks like the binary for Mac is in wrong format?

```
(libcst-env-1216) (base) jimmylai-mbp:LibCST jimmylai$ pyre check
 ƛ [Errno 8] Exec format error: '/Users/jimmylai/github/libcst-env-1216/bin/pyre.bin'
 ƛ Traceback (most recent call last):
  File "/Users/jimmylai/github/libcst-env-1216/lib/python3.7/site-packages/pyre_check/client/pyre.py", line 104, in main
    exit_code = command.run().exit_code()
  File "/Users/jimmylai/github/libcst-env-1216/lib/python3.7/site-packages/pyre_check/client/commands/command.py", line 497, in run
    self._run()
  File "/Users/jimmylai/github/libcst-env-1216/lib/python3.7/site-packages/pyre_check/client/commands/check.py", line 85, in _run
    result = self._call_client(command="check")
  File "/Users/jimmylai/github/libcst-env-1216/lib/python3.7/site-packages/pyre_check/client/commands/command.py", line 603, in _call_client
    preexec_fn=limit_memory_usage,
  File "/Users/jimmylai/anaconda3/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/Users/jimmylai/anaconda3/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/Users/jimmylai/github/libcst-env-1216/bin/pyre.bin'
```

CC @shannonzhu

**Comment by shannonzhu** [comment]
This version is removed for now as I figure out how to get the Mac compatible version released. Thanks for the report!
