### ISSUE TITLE
pyre-check 0.0.44+ is incompatible with python 3.6

### ISSUE THREAD

**Issue by ngonewd** [facebook/pyre-check#246]
When running pyre using python 3.6, the following error is produced:

```
No watchman binary found. 
To enable pyre incremental, you can install watchman: https://facebook.github.io/watchman/docs/install.html
Defaulting to non-incremental check.
 ƛ Traceback (most recent call last):
  File "/home/nick.gonella/.local/share/virtualenvs/fortknight-W434crmH/lib/python3.6/site-packages/pyre_check/client/pyre.py", line 98, in main
    exit_code = command.run().exit_code()
  File "/home/nick.gonella/.local/share/virtualenvs/fortknight-W434crmH/lib/python3.6/site-packages/pyre_check/client/commands/command.py", line 518, n
    self._run()
  File "/home/nick.gonella/.local/share/virtualenvs/fortknight-W434crmH/lib/python3.6/site-packages/pyre_check/client/commands/check.py", line 83, in n
    result = self._call_client(command="check")
  File "/home/nick.gonella/.local/share/virtualenvs/fortknight-W434crmH/lib/python3.6/site-packages/pyre_check/client/commands/command.py", line 624, t
    text=True,
TypeError: __init__() got an unexpected keyword argument 'text'
```

This seems to be the result of using the `text=True` keyword parameter of `subprocess.run`, which was introduced in python 3.7 and was not back ported.

**Comment by gbleaney** [comment]
Thanks for the report @ngonewd! I guess we were too excited to use the latest and greatest :). @MaggieMoss is working on fixing this, I'll let you know when we've shipped it.

**Comment by MaggieMoss** [comment]
@ngonewd @gbleaney should be resolved in this morning's release. Thanks again for flagging!
