### ISSUE TITLE
pyre-upgrade fails with `ModuleNotFoundError: No module named 'tools'`

### ISSUE THREAD

**Issue by jiridanek** [facebook/pyre-check#319]
I've installed pyre-check==0.0.56 and I've encountered the following error every time I try to run `pyre-upgrade`.

```
$ pyre-upgrade 
Traceback (most recent call last):
  File "/home/jdanek/.local/share/virtualenvs/dtests-szmMvKDj/bin/pyre-upgrade", line 5, in <module>
    from pyre_check.tools.upgrade.upgrade import main
  File "/home/jdanek/.local/share/virtualenvs/dtests-szmMvKDj/lib/python3.8/site-packages/pyre_check/tools/upgrade/upgrade.py", line 28, in <module>
    from .commands.strict_default import StrictDefault
  File "/home/jdanek/.local/share/virtualenvs/dtests-szmMvKDj/lib/python3.8/site-packages/pyre_check/tools/upgrade/commands/strict_default.py", line 11, in <module>
    from tools.pyre.client.find_directories import find_global_and_local_root
ModuleNotFoundError: No module named 'tools'
```

Is this something that is easily reproducible, or is there something weird in my setup that is breaking pyre-upgrade? I had to use an old version of pyre-check to be able to run pyre-upgrade. I used 0.0.46 which ran fine.

```
$ pip install pyre-check==0.0.56
Collecting pyre-check==0.0.56
  Using cached pyre_check-0.0.56-py3-none-manylinux1_x86_64.whl (24.6 MB)
Processing ./.cache/pip/wheels/ae/f3/c6/ffd1b0df0828cf685b0c863655f166b426cf1a3f62578206f1/pywatchman-1.4.1-cp38-cp38-linux_x86_64.whl
Collecting pyre-extensions
  Using cached pyre_extensions-0.0.18-py3-none-any.whl (8.3 kB)
Collecting libcst>=0.3.6
  Using cached libcst-0.3.12-py3-none-any.whl (501 kB)
Collecting dataclasses
  Using cached dataclasses-0.6-py3-none-any.whl (14 kB)
Processing ./.cache/pip/wheels/91/cf/b0/0c9998060b55ca80ea7a50a8639c3bdc6ba886eeff014bc9ac/psutil-5.7.2-cp38-cp38-linux_x86_64.whl
Collecting typing-inspect
  Using cached typing_inspect-0.6.0-py3-none-any.whl (8.1 kB)
Collecting typing-extensions
  Using cached typing_extensions-3.7.4.3-py3-none-any.whl (22 kB)
Collecting pyyaml>=5.2
  Downloading PyYAML-5.3.1.tar.gz (269 kB)
     |████████████████████████████████| 269 kB 1.1 MB/s 
Collecting mypy-extensions>=0.3.0
  Using cached mypy_extensions-0.4.3-py2.py3-none-any.whl (4.5 kB)
Using legacy setup.py install for pyyaml, since package 'wheel' is not installed.
Installing collected packages: pywatchman, mypy-extensions, typing-extensions, typing-inspect, pyre-extensions, pyyaml, libcst, dataclasses, psutil, pyre-check
    Running setup.py install for pyyaml ... done
Successfully installed dataclasses-0.6 libcst-0.3.12 mypy-extensions-0.4.3 psutil-5.7.2 pyre-check-0.0.56 pyre-extensions-0.0.18 pywatchman-1.4.1 pyyaml-5.3.1 typing-extensions-3.7.4.3 typing-inspect-0.6.0
WARNING: You are using pip version 20.1.1; however, version 20.2.3 is available.
You should consider upgrading via the '/home/jdanek/venv/bin/python -m pip install --upgrade pip' command.
```

**Comment by shannonzhu** [comment]
Thanks for reporting the issue! I've just released a new version where this is fixed; we will add some open source tests on the upgrade package to hopefully catch this problem in the future.
