### ISSUE TITLE
error on centos 7.4 & 7.5

### ISSUE THREAD

**Issue by cristgal** [facebook/pyre-check#4]
[root@c7-linpe-build ~]# pip3 install pyre-check
Collecting pyre-check
  Downloading https://files.pythonhosted.org/packages/e4/96/72a7048e5f340678c6eb48163b7bdc49926cdac2dff8bb5d935563e50b7f/pyre_check-0.0.5-py3-none-manylinux1_x86_64.whl (7.7MB)
    100% |████████████████████████████████| 7.7MB 3.5MB/s
Installing collected packages: pyre-check
Successfully installed pyre-check-0.0.5

[root@c7-linpe-build ~]# pyre
Traceback (most recent call last):
  File "/usr/bin/pyre", line 7, in <module>
    from pyre_check.pyre import main
  File "/usr/lib/python3.4/site-packages/pyre_check/__init__.py", line 151
    **normals,
     ^
SyntaxError: invalid syntax

[root@c7-linpe-build ~]# rpm -qi python34
Name        : python34
Version     : 3.4.8
Release     : 1.el7

[root@c7-linpe-build ~]# cat /etc/redhat-release
CentOS Linux release 7.5.1804 (Core)

**Comment by ambv** [comment]
Currently `pyre_check` is Python 3.6+ only but we should be able to make the runner work with 3.4+.

**Comment by dark** [comment]
@cristgal Thanks for the report. As @ambv mentioned, we use 3.6 for our development.
We will discuss with the team to see if it's feasible to support older release trains.

**Comment by dkgi** [comment]
Fixed this for 3.5 with #32. Unfortunately I was not able to get a python 3.4 working on my system.

**Comment by dark** [comment]
Version `0.0.6` will refuse to install on unsupported Python versions (<3.5 as of now).
