### ISSUE TITLE
Cannot initialize project

### ISSUE THREAD

**Issue by benzid-wael** [facebook/pyre-check#435]
# Pyre Bug

**Bug description**
Cannot initialize project

**Reproduction steps**
1. install pyre
2. Run: pyre init

Installed packages:
pyre-check==0.9.3
pyre-extensions==0.0.21

**Expected behavior**
Project initialized

**Logs**
Please include any relevant logs here:

```
Traceback (most recent call last):
  File "/Users/wael.benzid/miniconda2/envs/location-service/bin/pyre", line 5, in <module>
    from pyre_check.client.pyre import main
  File "/Users/wael.benzid/miniconda2/envs/location-service/lib/python3.7/site-packages/pyre_check/client/pyre.py", line 346, in <module>
    [command_arguments.TEXT, command_arguments.JSON], case_sensitive=False
TypeError: __init__() got an unexpected keyword argument 'case_sensitive'
```

Please run your reproduction steps followed by `pyre rage > pyre_rage.log`, and upload the file here:

empty file

**Additional context**
Add any other context about the problem here. (like dependencies in your venv, third party stub files being used, overall goals, etc.)

**Comment by grievejia** [comment]
What does `pip show click` says? The `case_sensitive` argument was added to `click` in version 7.0 and Pyre does rely on it.

**Comment by benzid-wael** [comment]
Hi @grievejia 

Below the requested output

```
$ pip show click

Name: click
Version: 8.0.1
Summary: Composable command line interface toolkit
Home-page: https://palletsprojects.com/p/click/
Author: Armin Ronacher
Author-email: armin.ronacher@active-4.com
License: BSD-3-Clause
Location: /Users/wael.benzid/miniconda2/envs/location-service/lib/python3.7/site-packages
Requires: importlib-metadata
Required-by: pyre-check, magic-wormhole, komsary, Flask, fb-sapp, csvdiff, click-log, black

```

**Comment by grievejia** [comment]
Hmm... That's weird. I couldn't repro this. 
```
> pyre init
ƛ Also initialize watchman in the current directory? [Y/n] n
ƛ Which directory(ies) should pyre analyze? (Default: `.`):
ƛ Successfully initialized pyre!
  You can view the configuration at `/Users/grievejia/scratch/foo/src/.pyre_configuration`.
  You can now run the type checker with `pyre`.
```
Could there be something else in your environments that mess up with the search path of the click library?

**Comment by cactuschibre** [comment]
I had the same problem and an upgrade of the `click` package fixed that:

```bash
pip install click --upgrade```
