### ISSUE TITLE
0.9.9 release getting rejected due to bad JSON ?

### ISSUE THREAD

**Issue by asah** [facebook/pyre-check#560]
hope this helps!

```
vagrant@f1d4849b5b15:~/zulip$ python3 -m pip install pyre-check
Defaulting to user installation because normal site-packages is not writeable
Collecting pyre-check
  Using cached pyre-check-0.9.9.tar.gz (12.7 MB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-4wc5hxaf/pyre-check_c856881ec5184156bdcd689155907af9/setup.py'"'"'; __file__='"'"'/tmp/pip-install-4wc5hxaf/pyre-check_c856881ec5184156bdcd689155907af9/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-mso6hulp
       cwd: /tmp/pip-install-4wc5hxaf/pyre-check_c856881ec5184156bdcd689155907af9/
  Complete output (13 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-4wc5hxaf/pyre-check_c856881ec5184156bdcd689155907af9/setup.py", line 146, in <module>
      main()
    File "/tmp/pip-install-4wc5hxaf/pyre-check_c856881ec5184156bdcd689155907af9/setup.py", line 140, in main
      runtime_dependencies=json.loads("""["dataclasses; python_version < \"3.7\"", "async-generator", "click", "dataclasses-json", "intervaltree", "libcst", "psutil", "pyre-extensions", "tabulate", "testslide>=2.7.0", "typing_extensions", ""]"""),
    File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
      return _default_decoder.decode(s)
    File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
      obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    File "/usr/lib/python3.6/json/decoder.py", line 355, in raw_decode
      obj, end = self.scan_once(s, idx)
  json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 34 (char 33)
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/e4/2d/097e5942e5fdd49beda9a0f5955238a21209e96bebe6fdad559b88caf3d8/pyre-check-0.9.9.tar.gz#sha256=a8245ed9a5a4fa21ee3e576aa4e8194d033cc13d0f5ccd84492fbfc68089f848 (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading pyre-check-0.9.3.tar.gz (15.3 MB)
     |████████████████████████████████| 15.3 MB 685 kB/s
  Preparing metadata (setup.py) ... done
vagrant@f1d4849b5b15:~/zulip$ python3 -V
Python 3.6.9

vagrant@f1d4849b5b15:~/zulip$ python3 -m pip -V
pip 21.3.1 from /home/vagrant/.local/lib/python3.6/site-packages/pip (python 3.6)

```

(I'm trying to compile [zulip](https://github.com/zulip/zulip)...)

**Comment by grievejia** [comment]
Should be fixed in 0.9.10
