### ISSUE TITLE
Oceans of pyre errors after changing to the new version

### ISSUE THREAD

**Issue by zhiqiand** [facebook/pyre-check#606]
# Pyre Bug
Recently I got the following pyre errors in Github Actions
```
Traceback (most recent call last):
  File "/usr/local/bin/pyre", line 5, in <module>
    from pyre_check.client.pyre import main
  File "/usr/local/lib/python3.8/dist-packages/pyre_check/client/pyre.py", line [17](https://github.com/terragraph/terragraph-planner/runs/6121101056?check_suite_focus=true#step:11:17), in <module>
    from . import (
  File "/usr/local/lib/python3.8/dist-packages/pyre_check/client/configuration/__init__.py", line 7, in <module>
    from .configuration import (  # noqa: F401
  File "/usr/local/lib/python3.8/dist-packages/pyre_check/client/configuration/configuration.py", line 34, in <module>
    from ..filesystem import expand_relative_path, expand_global_root
ImportError: cannot import name 'expand_global_root' from 'pyre_check.client.filesystem' (/usr/local/lib/python3.8/dist-packages/pyre_check/client/filesystem.py)
```
My guess is that pyre has a new version released so I changed the pyre version in `.pyre.configuration` file from 
`  "version": "0.0.101645531904"`
to:
`  "version": "0.0.101650366839"`
Thus the pyre version I downloaded in the Github Actions also changed.
After that, there are **oceans** of pyre errors occurred. For example, 
```
ƛ No watchman binary found. 
To enable pyre incremental, you can install watchman: https://facebook.github.io/watchman/docs/install

ƛ Defaulting to non-incremental check.

ƛ No binary specified, looking for `pyre.bin` in PATH
ƛ Could not determine the number of Pyre workers from configuration. Auto-set the value to 32.
ƛ Site package does not exist: `Pillow`

ƛ No typeshed specified, looking for it...
ƛ Could not find a suitable typeshed. Types for Python builtins and standard libraries may be missing!
...
ƛ Found 763 type errors!
....
Analysis failure [30]: Terminating analysis because type `xxxx` is not defined.
Undefined or invalid type [11]: Annotation `float` is not defined as a type.
Undefined import [21]: Could not find a module corresponding to import `json`.
Unused ignore [0]: The `pyre-ignore` or `pyre-fixme` comment is not suppressing type errors, please remove it.
```

**Expected behavior**
I am wondering if I could do something to make pyre turn back.

**Comment by xrival** [comment]
I am encountering the same issue when I try to set up a docker environment based on ubuntu, either on my own, or using the prototype Dockerfile from the pyre repository.
Is there any workaround ?
