### ISSUE TITLE
Not installing in arch linux

### ISSUE THREAD

**Issue by alfonso-higuera** [facebook/pyre-check#66]
$ python3.6 --version
Python 3.6.5

$ uname -a
Linux lahg 4.16.13-1-ARCH #1 SMP PREEMPT Thu May 31 23:29:29 UTC 2018 x86_64 GNU/Linux

$ python3.6 -m pip install pyre-check --user
Collecting pyre-check
  Could not find a version that satisfies the requirement pyre-check (from versions: )
No matching distribution found for pyre-check

$ pip3.6 install pyre-check --user
Collecting pyre-check
  Could not find a version that satisfies the requirement pyre-check (from versions: )
No matching distribution found for pyre-check

Similar to #11

**Comment by dark** [comment]
Hi @alfonso-higuera , I am not sure what's the reason behind the problem yet. Could you please run the following commands?
```
pip3.6 --version
python3.6 -m pip install pyre-check --user --verbose
pip3.6 install pyre-check --user --verbose
```
Thanks!

**Comment by alfonso-higuera** [comment]
Sure, thanks for the response, and sorry for taking so long to answer.

https://gist.github.com/alfonso-higuera/b9fad7e7b9e994f1b4e13bd56fa3d237

**Comment by dark** [comment]
Thanks for the info, I will look at the gist and let you know.

**Comment by kelly-apollo** [comment]
Environments:
```
Linux 965d148df725 4.9.49-moby #1 SMP Fri Dec 8 13:40:02 UTC 2017 x86_64 Linux
```

Commands: 

```
pip3.6 --version
python3.6 -m pip install pyre-check --user --verbose
pip3.6 install pyre-check --user --verbose
```
Outputs:
```
pip 10.0.1 from /usr/local/lib/python3.6/site-packages/pip (python 3.6)
Created temporary directory: /tmp/pip-ephem-wheel-cache-zwfazxzp
Created temporary directory: /tmp/pip-install-_lkreheh
Collecting pyre-check
  1 location(s) to search for versions of pyre-check:
  * https://pypi.org/simple/pyre-check/
  Getting page https://pypi.org/simple/pyre-check/
  Looking up "https://pypi.org/simple/pyre-check/" in the cache
  Current age based on date: 113
  Freshness lifetime from max-age: 600
  Freshness lifetime from request max-age: 600
  The response is "fresh", returning cached response
  600 > 113
  Analyzing links from page https://pypi.org/simple/pyre-check/
    Skipping link https://files.pythonhosted.org/packages/32/b0/8f074bf76214cafa5e88bbebc676df70396a66211333331790844df61adb/pyre_check-0.0.6-py3-none-macosx_10_11_x86_64.whl#sha256=2d631e00c15761bdeef0e3f70e3b54f8cfa2765018d42a841cbfe7373574db6d (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/f3/d9/f8382029c06b46b990628a71c04f8c8fd92adf2088e5d6cc92ea8b2c07d3/pyre_check-0.0.6-py3-none-manylinux1_x86_64.whl#sha256=a05d569441a1eadc5acbb8574710d69171898a2c02fa196e1d162faf77dc4f02 (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/7c/6b/fe0d1313d78f2d3edd2fbb1c9e7ded1ba06092916789baf163933844870e/pyre_check-0.0.7-py3-none-macosx_10_11_x86_64.whl#sha256=1ca118242d4c3cee4ddf8d55234064ff1b16288c56949ff55e85c4d2dec6fd67 (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/dd/c1/89a1daa94e1c5be6d66e3b259a323fa38eca7a3305186a39bbc5a8d807a2/pyre_check-0.0.7-py3-none-manylinux1_x86_64.whl#sha256=a9ed2d1a16e14cdf8248045dbf9f8ec0089e0f6c8dfc9c1262de1c6c103bbb6b (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5); it is not compatible with this Python
Cleaning up...
Exception information:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/basecommand.py", line 228, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 291, in run
    resolver.resolve(requirement_set)
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/resolve.py", line 103, in resolve
    self._resolve_one(requirement_set, req)
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/resolve.py", line 257, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/resolve.py", line 210, in _get_abstract_dist_for
    self.require_hashes
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 245, in prepare_linked_requirement
    req.populate_link(finder, upgrade_allowed, require_hashes)
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 307, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/index.py", line 533, in find_requirement
    'No matching distribution found for %s' % req
pip._internal.exceptions.DistributionNotFound: No matching distribution found for pyre-check
Created temporary directory: /tmp/pip-ephem-wheel-cache-yidegae2
Created temporary directory: /tmp/pip-install-ic5b2snv
Collecting pyre-check
  1 location(s) to search for versions of pyre-check:
  * https://pypi.org/simple/pyre-check/
  Getting page https://pypi.org/simple/pyre-check/
  Looking up "https://pypi.org/simple/pyre-check/" in the cache
  Current age based on date: 114
  Freshness lifetime from max-age: 600
  Freshness lifetime from request max-age: 600
  The response is "fresh", returning cached response
  600 > 114
  Analyzing links from page https://pypi.org/simple/pyre-check/
    Skipping link https://files.pythonhosted.org/packages/32/b0/8f074bf76214cafa5e88bbebc676df70396a66211333331790844df61adb/pyre_check-0.0.6-py3-none-macosx_10_11_x86_64.whl#sha256=2d631e00c15761bdeef0e3f70e3b54f8cfa2765018d42a841cbfe7373574db6d (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/f3/d9/f8382029c06b46b990628a71c04f8c8fd92adf2088e5d6cc92ea8b2c07d3/pyre_check-0.0.6-py3-none-manylinux1_x86_64.whl#sha256=a05d569441a1eadc5acbb8574710d69171898a2c02fa196e1d162faf77dc4f02 (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/7c/6b/fe0d1313d78f2d3edd2fbb1c9e7ded1ba06092916789baf163933844870e/pyre_check-0.0.7-py3-none-macosx_10_11_x86_64.whl#sha256=1ca118242d4c3cee4ddf8d55234064ff1b16288c56949ff55e85c4d2dec6fd67 (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/dd/c1/89a1daa94e1c5be6d66e3b259a323fa38eca7a3305186a39bbc5a8d807a2/pyre_check-0.0.7-py3-none-manylinux1_x86_64.whl#sha256=a9ed2d1a16e14cdf8248045dbf9f8ec0089e0f6c8dfc9c1262de1c6c103bbb6b (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5); it is not compatible with this Python
Cleaning up...
Exception information:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/basecommand.py", line 228, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 291, in run
    resolver.resolve(requirement_set)
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/resolve.py", line 103, in resolve
    self._resolve_one(requirement_set, req)
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/resolve.py", line 257, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/resolve.py", line 210, in _get_abstract_dist_for
    self.require_hashes
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 245, in prepare_linked_requirement
    req.populate_link(finder, upgrade_allowed, require_hashes)
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 307, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/index.py", line 533, in find_requirement
    'No matching distribution found for %s' % req
pip._internal.exceptions.DistributionNotFound: No matching distribution found for pyre-check

```

**Comment by alfonso-higuera** [comment]
@dark Thanks again for your help.  You were right, I have a pip config file that prevented the installation of binaries.  Even though I don't remember writing it I highly doubt it's an Arch default config file.  I suggest to close this issue.

**Comment by dark** [comment]
@alfonso-higuera Great, glad I could help.

@kelly-apollo The error you posted looks different:
```
[...] (requires-python:>=3.5); it is not compatible with this Python
```
I'd rather not conflate different reports, could you please open a new issue? Thanks.
