### ISSUE TITLE
Allow pyre to read configuration from pyproject.toml

### ISSUE THREAD

**Issue by ChillarAnand** [facebook/pyre-check#695]
# Pyre Feature Request

Having custom config files for each tool is fine. Since most tools use pyproject.toml file for configuration, if pyre supports configuration using it, it would be great.

**Comment by quantumpacket** [comment]
@sthagen this commit causes Pyre to break.

```
Traceback (most recent call last):
  File ".venv/lib/python3.13/site-packages/pyre_check/client/pyre.py", line 1560, in main
    return_code = pyre(argv, auto_envvar_prefix="PYRE", standalone_mode=False)
  File ".venv/lib/python3.13/site-packages/click/core.py", line 1161, in __call__
    return self.main(*args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.13/site-packages/click/core.py", line 1082, in main
    rv = self.invoke(ctx)
  File ".venv/lib/python3.13/site-packages/click/core.py", line 1697, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File ".venv/lib/python3.13/site-packages/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.13/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
  File ".venv/lib/python3.13/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File ".venv/lib/python3.13/site-packages/pyre_check/client/pyre.py", line 729, in check
    return _run_check_command(context.obj["arguments"])
  File ".venv/lib/python3.13/site-packages/pyre_check/client/pyre.py", line 87, in _run_check_command
    configuration = _create_and_check_configuration(arguments, Path("."))
  File ".venv/lib/python3.13/site-packages/pyre_check/client/pyre.py", line 175, in _create_and_check_configuration
    configuration = configuration_module.create_configuration(arguments, base_directory)
  File ".venv/lib/python3.13/site-packages/pyre_check/client/configuration/configuration.py", line 1011, in create_configuration
    partial_configuration = PartialConfiguration.from_file(
                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        project_root / TOML_CONFIGURATION_FILE
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ).expand_relative_paths(str(project_root))
    ^
  File ".venv/lib/python3.13/site-packages/pyre_check/client/configuration/configuration.py", line 515, in from_file
    configuration_toml = tomllib.loads(contents)["tool"]["pyre"]
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'pyre'
```

I have to put an empty `[tool.pyre]` section in my `pyproject.toml` file to avoid this breakage.

**Comment by yangdanny97** [comment]
@quantumpacket

https://github.com/facebook/pyre-check/commit/fa7858c0821fd3d312fbeedf28044e029028f5d2 should fix that issue. 

Are you running pyre without a configuration file?

**Comment by quantumpacket** [comment]
> Are you running pyre without a configuration file?

Yes, just using default settings. No Pyre config file or Pyre config section being used.
