### ISSUE TITLE
Installation fails on Ubuntu

### ISSUE THREAD

**Issue by jgarvin** [facebook/pyre-check#702]
I have run the command from the docs:

```
sudo apt-get install python3 python3-pip python3-venv watchman
```

And then I try:

```
pip install pyre-check
```

And I get:

```
$ pip3 install pyre
Collecting pyre
  Using cached pyre-1.11.2.tar.gz (2.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: PyYAML in /usr/lib/python3/dist-packages (from pyre) (5.3.1)
Building wheels for collected packages: pyre
  Building wheel for pyre (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /tmp/tmpbrw40wtc build_wheel /tmp/tmpu9jsvq2n
       cwd: /tmp/pip-install-t_yzp6hh/pyre
  Complete output (121 lines):
  
  
  --------------------------------------------------------------------------------
  -- Trying "Ninja" generator
  --------------------------------
  ---------------------------
  ----------------------
  -----------------
  ------------
  -------
  --
  Not searching for unused variables given on the command line.
  -- The C compiler identification is GNU 9.4.0
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /usr/bin/cc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- The CXX compiler identification is GNU 9.4.0
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Configuring done
  -- Generating done
  -- Build files have been written to: /tmp/pip-install-t_yzp6hh/pyre/_cmake_test_compile/build
  --
  -------
  ------------
  -----------------
  ----------------------
  ---------------------------
  --------------------------------
  -- Trying "Ninja" generator - success
  --------------------------------------------------------------------------------
  
  Configuring Project
    Working directory:
      /tmp/pip-install-t_yzp6hh/pyre/_skbuild/linux-x86_64-3.8/cmake-build
    Command:
      cmake /tmp/pip-install-t_yzp6hh/pyre -G Ninja -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-install-t_yzp6hh/pyre/_skbuild/linux-x86_64-3.8/cmake-install -DPYTHON_VERSION_STRING:STRING=3.8.10 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/pip-build-env-cl96ff3w/overlay/lib/python3.8/site-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/usr/bin/python3 -DPYTHON_INCLUDE_DIR:PATH=/usr/include/python3.8 -DPYTHON_LIBRARY:PATH=/usr/lib/x86_64-linux-gnu/libpython3.8.so -DPython_EXECUTABLE:PATH=/usr/bin/python3 -DPython_ROOT_DIR:PATH=/usr -DPython_INCLUDE_DIR:PATH=/usr/include/python3.8 -DPython_FIND_REGISTRY:STRING=NEVER -DPython_NumPy_INCLUDE_DIRS:PATH=/tmp/pip-build-env-cl96ff3w/overlay/lib/python3.8/site-packages/numpy/core/include -DPython3_EXECUTABLE:PATH=/usr/bin/python3 -DPython3_ROOT_DIR:PATH=/usr -DPython3_INCLUDE_DIR:PATH=/usr/include/python3.8 -DPython3_FIND_REGISTRY:STRING=NEVER -DPython3_NumPy_INCLUDE_DIRS:PATH=/tmp/pip-build-env-cl96ff3w/overlay/lib/python3.8/site-packages/numpy/core/include -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/pip-build-env-cl96ff3w/overlay/lib/python3.8/site-packages/ninja/data/bin/ninja -Dpybind11_DIR=/tmp/pip-build-env-cl96ff3w/overlay/lib/python3.8/site-packages/pybind11/share/cmake/pybind11 -DPYRE_VERSION=1.11.2 -DPYRE_DEST_PACKAGES=lib/python3.8/site-packages -DCMAKE_BUILD_TYPE:STRING=Release
  
  -- The CXX compiler identification is GNU 9.4.0
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Found MPI_CXX: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_cxx.so (found version "3.1")
  -- Found MPI: TRUE (found version "3.1") found components: CXX
  -- Could NOT find GSL (missing: GSL_INCLUDE_DIR GSL_LIBRARY GSL_CBLAS_LIBRARY) (found version "")
  parallel hdf5: ON
  -- Could NOT find HDF5 (missing: HDF5_LIBRARIES HDF5_INCLUDE_DIRS HDF5_HL_LIBRARIES CXX HL) (found version "")
  -- Could NOT find PostgreSQL (missing: PostgreSQL_LIBRARY PostgreSQL_INCLUDE_DIR)
  -- Found Python: /usr/bin/python3 (found suitable version "3.8.10", minimum required is "3.7") found components: Interpreter Development NumPy Development.Module Development.Embed
  -- Performing Test HAS_FLTO
  -- Performing Test HAS_FLTO - Success
  -- Found pybind11: /tmp/pip-build-env-cl96ff3w/overlay/lib/python3.8/site-packages/pybind11/include (found version "2.10.3")
  CMake Warning (dev) at .cmake/pyre_mpi.cmake:47 (file):
    CONFIGURE_DEPENDS flag was given after a glob expression was already
    evaluated.
  Call Stack (most recent call first):
    lib/CMakeLists.txt:15 (pyre_mpiLib)
  This warning is for project developers.  Use -Wno-dev to suppress it.
  
  -- The C compiler identification is GNU 9.4.0
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /usr/bin/cc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Configuring done
  CMake Error at .cmake/pyre_h5.cmake:18 (target_link_libraries):
    Target "h5module" links to:
  
      HDF5::HDF5
  
    but the target was not found.  Possible reasons include:
  
      * There is a typo in the target name.
      * A find_package call is missing for an IMPORTED target.
      * An ALIAS target is missing.
  
  Call Stack (most recent call first):
    extensions/CMakeLists.txt:17 (pyre_h5Module)
  
  
  -- Generating done
  CMake Warning:
    Manually-specified variables were not used by the project:
  
      PYTHON_EXECUTABLE
      PYTHON_INCLUDE_DIR
      PYTHON_LIBRARY
      PYTHON_VERSION_STRING
      Python3_EXECUTABLE
      Python3_FIND_REGISTRY
      Python3_INCLUDE_DIR
      Python3_NumPy_INCLUDE_DIRS
      Python3_ROOT_DIR
      SKBUILD
  
  
  CMake Generate step failed.  Build files cannot be regenerated correctly.
  /tmp/pip-build-env-cl96ff3w/overlay/lib/python3.8/site-packages/setuptools/config/pyprojecttoml.py:108: _BetaConfiguration: Support for `[tool.setuptools]` in `pyproject.toml` is still *beta*.
    warnings.warn(msg, _BetaConfiguration)
  Traceback (most recent call last):
    File "/tmp/pip-build-env-cl96ff3w/overlay/lib/python3.8/site-packages/skbuild/setuptools_wrap.py", line 632, in setup
      env = cmkr.configure(
    File "/tmp/pip-build-env-cl96ff3w/overlay/lib/python3.8/site-packages/skbuild/cmaker.py", line 335, in configure
      raise SKBuildError(
  
  An error occurred while configuring with CMake.
    Command:
      cmake /tmp/pip-install-t_yzp6hh/pyre -G Ninja -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-install-t_yzp6hh/pyre/_skbuild/linux-x86_64-3.8/cmake-install -DPYTHON_VERSION_STRING:STRING=3.8.10 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/pip-build-env-cl96ff3w/overlay/lib/python3.8/site-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/usr/bin/python3 -DPYTHON_INCLUDE_DIR:PATH=/usr/include/python3.8 -DPYTHON_LIBRARY:PATH=/usr/lib/x86_64-linux-gnu/libpython3.8.so -DPython_EXECUTABLE:PATH=/usr/bin/python3 -DPython_ROOT_DIR:PATH=/usr -DPython_INCLUDE_DIR:PATH=/usr/include/python3.8 -DPython_FIND_REGISTRY:STRING=NEVER -DPython_NumPy_INCLUDE_DIRS:PATH=/tmp/pip-build-env-cl96ff3w/overlay/lib/python3.8/site-packages/numpy/core/include -DPython3_EXECUTABLE:PATH=/usr/bin/python3 -DPython3_ROOT_DIR:PATH=/usr -DPython3_INCLUDE_DIR:PATH=/usr/include/python3.8 -DPython3_FIND_REGISTRY:STRING=NEVER -DPython3_NumPy_INCLUDE_DIRS:PATH=/tmp/pip-build-env-cl96ff3w/overlay/lib/python3.8/site-packages/numpy/core/include -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/pip-build-env-cl96ff3w/overlay/lib/python3.8/site-packages/ninja/data/bin/ninja -Dpybind11_DIR=/tmp/pip-build-env-cl96ff3w/overlay/lib/python3.8/site-packages/pybind11/share/cmake/pybind11 -DPYRE_VERSION=1.11.2 -DPYRE_DEST_PACKAGES=lib/python3.8/site-packages -DCMAKE_BUILD_TYPE:STRING=Release
    Source directory:
      /tmp/pip-install-t_yzp6hh/pyre
    Working directory:
      /tmp/pip-install-t_yzp6hh/pyre/_skbuild/linux-x86_64-3.8/cmake-build
  Please see CMake's output for more information.
  ----------------------------------------
  ERROR: Failed building wheel for pyre
Failed to build pyre
ERROR: Could not build wheels for pyre which use PEP 517 and cannot be installed directly
```

**Comment by jgarvin** [comment]
I was able to fix this by adding `libhdf5-dev` to the list of `apt-get` packages, that should probably go in the docs.

**Comment by jgarvin** [comment]
argh this is the wrong package `pyre-check` not `pyre`
