### ISSUE TITLE
Pyre installation procedure results in a mac os Mach binary installed in a Debian x86_i64 system

### ISSUE THREAD

**Issue by sarraga** [facebook/pyre-check#907]
# Pyre Bug

**Bug description**
Pyre installation procedure results in a mac os Mach binary installed in a Debian x86_i64 system

**Reproduction steps**
From my .history

  502  . learn/data_oriented_programming/.venv/bin/activate
  503  cd learn/
  504  cd data_oriented_programming/
 ... irrelevant commands.
  521  sudo apt-get install python3 python3-pip python3-venv watchman
  522  man watchman
  523  pyre
  524  pip install pyre-check
  525  pyre init
  
**Expected behavior**
A working x86_i64 pyre binary installed in my system.

**Logs**
Please include any relevant logs here:
ƛ [Errno 8] Exec format error: '/home/sarraga/learn/data_oriented_programming/.venv/bin/pyre.bin'
Traceback (most recent call last):
  File "/home/sarraga/learn/data_oriented_programming/.venv/lib/python3.9/site-packages/pyre_check/client/pyre.py", line 1641, in main
    return_code = pyre(argv, auto_envvar_prefix="PYRE", standalone_mode=False)
  File "/home/sarraga/learn/data_oriented_programming/.venv/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/sarraga/learn/data_oriented_programming/.venv/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/sarraga/learn/data_oriented_programming/.venv/lib/python3.9/site-packages/click/core.py", line 1667, in invoke
    return _process_result([] if self.chain else rv)
  File "/home/sarraga/learn/data_oriented_programming/.venv/lib/python3.9/site-packages/click/core.py", line 1657, in _process_result
    value = ctx.invoke(self._result_callback, value, **ctx.params)
  File "/home/sarraga/learn/data_oriented_programming/.venv/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/sarraga/learn/data_oriented_programming/.venv/lib/python3.9/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/sarraga/learn/data_oriented_programming/.venv/lib/python3.9/site-packages/pyre_check/client/pyre.py", line 1621, in run_default_command
    return _run_default_command(command_argument)
  File "/home/sarraga/learn/data_oriented_programming/.venv/lib/python3.9/site-packages/pyre_check/client/pyre.py", line 124, in _run_default_command
    return _run_incremental_command(
  File "/home/sarraga/learn/data_oriented_programming/.venv/lib/python3.9/site-packages/pyre_check/client/pyre.py", line 110, in _run_incremental_command
    return commands.incremental.run(
  File "/home/sarraga/learn/data_oriented_programming/.venv/lib/python3.9/site-packages/pyre_check/client/commands/incremental.py", line 213, in run
    return run_incremental(configuration, incremental_arguments)
  File "/home/sarraga/learn/data_oriented_programming/.venv/lib/python3.9/site-packages/pyre_check/client/commands/incremental.py", line 187, in run_incremental
    start_status = start.run(configuration, incremental_arguments.start_arguments)
  File "/home/sarraga/learn/data_oriented_programming/.venv/lib/python3.9/site-packages/pyre_check/client/commands/start.py", line 569, in run
    return _run_in_background(
  File "/home/sarraga/learn/data_oriented_programming/.venv/lib/python3.9/site-packages/pyre_check/client/commands/start.py", line 484, in _run_in_background
    server_process = subprocess.Popen(
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/sarraga/learn/data_oriented_programming/.venv/bin/pyre.bin'
(dop) sarraga@nagios:~/learn/data_oriented_programming$ file /home/sarraga/learn/data_oriented_programming/.venv/bin/pyre.bin
/home/sarraga/learn/data_oriented_programming/.venv/bin/pyre.bin: Mach-O 64-bit x86_64 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|WEAK_DEFINES|BINDS_TO_WEAK|PIE|HAS_TLV_DESCRIPTORS>
(dop) sarraga@nagios:~/learn/data_oriented_programming$ uname -a
Linux nagios 6.0.2-x86_64-linode157 #1 SMP PREEMPT_DYNAMIC Mon Oct 17 13:01:41 EDT 2022 x86_64 GNU/Linux
(dop) sarraga@nagios:~/learn/data_oriented_programming$

```
Output goes here
```

Please run your reproduction steps followed by `pyre rage > pyre_rage.log`, and upload the file here:

pyre can't execute, so this step can't be completed.

<FILE>

**Additional context**
Add any other context about the problem here. (like dependencies in your venv, third party stub files being used, overall goals, etc.)

**Comment by connernilsen** [comment]
Hey @sarraga, unfortunately, our releases are for limited architectures and aren't done very often. If you're running into this, I recommend just building from source if possible (which I see you've been looking at with #908). 

We'd like to get more frequent releases out for Pyre in the future, and for more architectures, but it's not something we can prioritize at the moment. This will likely be something we can do in the next year though!
