### ISSUE TITLE
Error on pyre init

### ISSUE THREAD

**Issue by jasonkuhrt** [facebook/pyre-check#98]
```
$ pip install pyre-check
Collecting pyre-check
  Downloading https://files.pythonhosted.org/packages/0f/d4/e36fe2d30d9a46d1b80860a9d0bd34b8aab25b7e8a55a2feae8c6b84437a/pyre_check-0.0.11-py3-none-macosx_10_11_x86_64.whl (11.6MB)
    100% |████████████████████████████████| 11.6MB 135kB/s
Installing collected packages: pyre-check
Successfully installed pyre-check-0.0.11
You are using pip version 9.0.3, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

$ pyre init
 ƛ 'NoneType' object has no attribute 'logger'
 ƛ Traceback (most recent call last):
  File "/Users/jasonkuhrt/.pyenv/versions/3.6.5/envs/kappa/lib/python3.6/site-packages/pyre_check/pyre.py", line 320, in main
    arguments.command(arguments, configuration, analysis_directory)
  File "/Users/jasonkuhrt/.pyenv/versions/3.6.5/envs/kappa/lib/python3.6/site-packages/pyre_check/commands/initialize.py", line 25, in __init__
    super(Initialize, self).__init__(arguments, configuration, analysis_directory)
  File "/Users/jasonkuhrt/.pyenv/versions/3.6.5/envs/kappa/lib/python3.6/site-packages/pyre_check/commands/command.py", line 73, in __init__
    self._logger = arguments.logger or configuration.logger
AttributeError: 'NoneType' object has no attribute 'logger'
```

**Comment by dark** [comment]
I'm guilty as charged. Thanks for the report!

**Comment by dark** [comment]
This is fixed in master, planning to tag a release in the next few days.
